"""Workflow AST: structured plans with symbolic variable references.

The LLM generates workflows as JSON that we parse into these models.
Symbolic references (@var_name) keep concrete data out of the plan,
enforcing separation of code and data.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, model_validator


class SymRef(BaseModel):
    """Symbolic variable reference, e.g. @emails_fetched.

    These are placeholders in the workflow AST. They get bound
    to concrete values only at execution time.
    """

    ref: str

    def __str__(self) -> str:
        return f"@{self.ref}"

    def __repr__(self) -> str:
        return f"SymRef({self.ref!r})"

    def __hash__(self) -> int:
        return hash(self.ref)

    def __eq__(self, other: object) -> bool:
        return isinstance(other, SymRef) and self.ref == other.ref


def _normalize_refs(val: Any) -> Any:
    """Recursively normalize {"ref": "x"} dicts to SymRef objects.

    A dict is converted only when it has exactly one key and that key
    is "ref" with a string value.  All other dicts (including those
    that happen to contain a "ref" key alongside other keys) are left
    as literal dicts with their values recursively normalized.
    """
    if isinstance(val, dict):
        if len(val) == 1 and "ref" in val and isinstance(val["ref"], str):
            return SymRef(ref=val["ref"])
        return {k: _normalize_refs(v) for k, v in val.items()}
    if isinstance(val, list):
        return [_normalize_refs(v) for v in val]
    return val


class ToolCallNode(BaseModel):
    """A single tool invocation in the workflow."""

    tool_name: str
    arguments: dict[str, Any] = {}
    result_binding: str | None = None

    @model_validator(mode="after")
    def _normalize_arguments(self) -> "ToolCallNode":
        self.arguments = {
            k: _normalize_refs(v) for k, v in self.arguments.items()
        }
        return self


class ConditionalNode(BaseModel):
    """A conditional branch in the workflow."""

    condition: str
    then_steps: list[WorkflowStep] = []
    else_steps: list[WorkflowStep] = []


class LoopNode(BaseModel):
    """Iterate over a symbolic collection."""

    collection_ref: str
    item_binding: str
    body: list[WorkflowStep] = []


class WorkflowStep(BaseModel):
    """A single step in the workflow. Exactly one of the variant fields is set."""

    label: str
    tool_call: ToolCallNode | None = None
    conditional: ConditionalNode | None = None
    loop: LoopNode | None = None

    @model_validator(mode="after")
    def _exactly_one_variant(self) -> "WorkflowStep":
        set_fields = sum(
            1 for f in (self.tool_call, self.conditional, self.loop) if f is not None
        )
        if set_fields != 1:
            raise ValueError(
                f"WorkflowStep '{self.label}' must have exactly one of "
                f"tool_call, conditional, or loop (got {set_fields})"
            )
        return self


class Workflow(BaseModel):
    """Complete workflow AST generated by the LLM."""

    goal: str
    steps: list[WorkflowStep]
    input_variables: list[str] = []


# Rebuild forward refs for recursive models
ConditionalNode.model_rebuild()
LoopNode.model_rebuild()
WorkflowStep.model_rebuild()
